[template]
description = "A Rust template for easily starting NumWorks app development using the EADKP library"
project_name_case = "snake_case"
exclude = ["assets/*", "justfile"]

ignore = ["bootstrap.sh"]