version: "3.9"

services:
  eadkp-dev:
    build: 
      context: https://github.com/Oignontom8283/eadkp.git#dev
      dockerfile: dockerfile
    image: nraddi:latest
    container_name: {{project-name}}
    working_dir: /workspace/{{project-name}}
    volumes:
      - ./:/workspace/{{project-name}}
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Mount the entire USB bus to allow hotplug support
      - /dev/bus/usb:/dev/bus/usb
      # Provide access to GPU rendering (required for graphical apps / OpenGL)
      - /dev/dri:/dev/dri
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      # Uncomment for detailed libusb debugging
      # - LIBUSB_DEBUG=3
    device_cgroup_rules:
      - 'c 189:* rmw'   # All USB devices (major 189)
      - 'c 166:* rmw'   # ttyACM devices (kernel-dependent / not always required)
      - 'c 204:* rmw'   # ttyAMA or alternatives (kernel-dependent)

# Only works on Linux hosts (or via WSL with an X server for Windows) using X11.
# Wayland is not supported at the moment.
# For macOS, you would probably need to use an external X11 server (XQuartz) and mount the appropriate socket. (not tested)
